# @depreacted use semantic-release
on:
  push:
    tags:
      - "v*"
name: gh-pages-release
jobs:
  github-release:
    if: github.repository == 'snolab/CapsLockX'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # Github release with changelog
      - run: npx -y -- github-release-from-cc-changelog ${{ env.RELEASE_VERSION }}
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # pack
      - run: mkdir -p ./CapsLockX-${{ env.RELEASE_VERSION }}
      - run: cp -r docs Core Data Modules Tools *.exe *.ahk *.md ./CapsLockX-${{ env.RELEASE_VERSION }}
      - run: zip -r CapsLockX-${{ env.RELEASE_VERSION }}.zip ./CapsLockX-${{ env.RELEASE_VERSION }} -UN=UTF8
      # upload
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: CapsLockX-${{ env.RELEASE_VERSION }}.zip
          tag: ${{ github.ref }}
      # push to gh pages
      - run: cp CapsLockX-${{ env.RELEASE_VERSION }}.zip docs/CapsLockX-${{ env.RELEASE_VERSION }}.zip
      - run: cp CapsLockX-${{ env.RELEASE_VERSION }}.zip docs/CapsLockX-latest.zip
      - run: cp CHANGELOG.md docs/CHANGELOG.md
      - run: cp Core/version.txt docs/version.txt
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: true
